---
title: "OmicLoupe: Quality report"
output: html_document
params:
    n: NA
    input: NA
    make_ref_barplot: NA
    make_comp_barplot: NA
    make_ref_boxplot: NA
    make_comp_boxplot: NA
    make_ref_density: NA
    make_comp_density: NA
    make_ref_dendrogram: NA
    make_comp_dendrogram: NA
---

```{r echo=FALSE}
input <- params$input
error_check <- function(func) {
    tryCatch({
        func()
    },
    error=function(e) {
        print("An error was encountered. Please sure the plots are showing up correctly in OmicLoupe before export.")
        print("If not helping, please contact the developers for further support")
        print("Error message: ")
        print(e)
    })
}
```

# Boxplots

```{r echo=FALSE}
error_check(params$make_ref_boxplot)
```

```{r echo=FALSE}
error_check(params$make_comp_boxplot)
```

# Density

```{r echo=FALSE}
error_check(params$make_ref_density)
```

```{r echo=FALSE}
error_check(params$make_comp_density)
```

# Barplots

```{r echo=FALSE}
error_check(params$make_ref_barplot)
```

```{r echo=FALSE}
error_check(params$make_comp_barplot)
```

# Dendrogram

```{r echo=FALSE}
error_check(params$make_ref_dendrogram)
```

```{r echo=FALSE}
error_check(params$make_comp_dendrogram)
```

# Settings 

```{r echo=FALSE}
settings_df <- params$input %>% 
    unlist() %>% 
    data.frame() %>% 
    rownames_to_column() %>% 
    `colnames<-`(c("Name", "Value")) # %>%
    # mutate(Category=gsub("\\..*", "", Name)) %>%
    # mutate(Name=gsub("quality_settings\\.", "", Name)) %>%
    # dplyr::select(Category, Name, Value)

DT::datatable(settings_df)

# as.data.frame(params$input) %>% rownames_to_column("setting")
```


# Environment

```{r echo=FALSE}
sessionInfo()
```





