---
title: "OmicLoupe: Statistical distributions report"
output: html_document
params:
    n: NA
    input: NA
    setup_input: NA
    make_ref_volcano: NA
    make_comp_volcano: NA
    make_ref_ma: NA
    make_comp_ma: NA
    make_ref_phist: NA
    make_comp_phist: NA
---

```{r echo=FALSE}
input <- params$input
error_check <- function(func) {
    tryCatch({
        func()
    },
    error=function(e) {
        print("An error was encountered. Please sure the plots are showing up correctly in OmicLoupe before export.")
        print("If not helping, please contact the developers for further support")
        print("Error message: ")
        print(e)
    })
}
```

# Plots

## Volcano plots

```{r echo=FALSE}
error_check(params$make_ref_volcano)
```

```{r echo=FALSE}
error_check(params$make_comp_volcano)
```

## MA plots

```{r echo=FALSE}
error_check(params$make_ref_ma)
```

```{r echo=FALSE}
error_check(params$make_comp_ma)
```

## P-value histogram

```{r echo=FALSE}
error_check(params$make_ref_phist)
```

```{r echo=FALSE}
error_check(params$make_comp_phist)
```

# Settings 

```{r echo=FALSE, results=FALSE}
library(tidyverse)
library(DT)
library(shiny)
```

## Tab settings

Current tab

```{r echo=FALSE}
settings_df <- params$input %>% 
    reactiveValuesToList() %>%
    unlist() %>%
    data.frame() %>%
    rownames_to_column() %>%
    `colnames<-`(c("Name", "Value"))
DT::datatable(settings_df)
```

Setup tab

```{r echo=FALSE}
setup_settings_df <- params$setup_input %>%
    reactiveValuesToList() %>%
    unlist() %>%
    data.frame() %>%
    rownames_to_column() %>%
    `colnames<-`(c("Name", "Value"))
DT::datatable(setup_settings_df)
```

# Environment

```{r echo=FALSE}
sessionInfo()
```
